/**
 * Accounting — جداول المحاسبة: الحسابات، القيود، الفواتير
 * هذا الجزء يتطلب ACID كامل — سبب رئيسي للانتقال لـ PostgreSQL
 */
import {
  pgTable,
  uuid,
  varchar,
  text,
  boolean,
  timestamp,
  integer,
  bigint,
  jsonb,
  date,
  index,
  unique,
  check,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import {
  accountTypeEnum,
  accountSideEnum,
  journalEntryTypeEnum,
  journalEntryStatusEnum,
  invoiceTypeEnum,
  invoiceStatusEnum,
  paymentStatusEnum,
  zatcaInvoiceTypeCodeEnum,
  zatcaSubmissionStatusEnum,
  zatcaTransactionTypeEnum,
  vatCategoryEnum,
  paymentMethodEnum,
} from './enums.js';
import { agencies } from './agencies.js';
import { users } from './users.js';
import { bookings } from './bookings.js';

// ─── دليل الحسابات ────────────────────────────────────────────────────────────

/**
 * دليل الحسابات — Chart of Accounts
 * كل وكالة تمتلك دليل حسابات خاص بها
 */
export const chartOfAccounts = pgTable(
  'chart_of_accounts',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    agencyId: uuid('agency_id')
      .notNull()
      .references(() => agencies.id, { onDelete: 'cascade' }),

    code: varchar('code', { length: 20 }).notNull(),
    nameAr: varchar('name_ar', { length: 200 }).notNull(),
    nameEn: varchar('name_en', { length: 200 }).notNull(),

    type: accountTypeEnum('type').notNull(),
    normalSide: accountSideEnum('normal_side').notNull(),

    // الرصيد الحالي (بالهللات) — يُحدَّث عند كل قيد
    // bigint لأن الأرصدة قد تتجاوز 2 مليار هللة
    balanceHalalas: bigint('balance_halalas', { mode: 'bigint' })
      .notNull()
      .default(0n),

    // الهرمية (للتقارير المجمعة)
    parentCode: varchar('parent_code', { length: 20 }),
    level: integer('level').notNull().default(1),

    // خيارات الحساب
    isActive: boolean('is_active').notNull().default(true),
    isSystem: boolean('is_system').notNull().default(false), // حسابات لا يمكن حذفها
    allowManualEntry: boolean('allow_manual_entry').notNull().default(true),

    description: text('description'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    unique('coa_agency_code_unique').on(t.agencyId, t.code),
    index('coa_agency_id_idx').on(t.agencyId),
    index('coa_type_idx').on(t.agencyId, t.type),
    index('coa_parent_code_idx').on(t.agencyId, t.parentCode),
  ]
);

// ─── القيود اليومية ───────────────────────────────────────────────────────────

/**
 * القيود اليومية — Journal Entries
 * APPEND-ONLY: لا تُحذف ولا تُعدَّل بعد الاعتماد
 * إلغاء القيد يتم بإنشاء قيد عكسي (reversal)
 */
export const journalEntries = pgTable(
  'journal_entries',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    agencyId: uuid('agency_id')
      .notNull()
      .references(() => agencies.id, { onDelete: 'restrict' }),

    type: journalEntryTypeEnum('type').notNull(),
    description: text('description').notNull(),

    // التاريخ المحاسبي (قد يختلف عن تاريخ الإنشاء)
    entryDate: date('entry_date').notNull(),
    // الفترة المحاسبية (YYYY-MM)
    period: varchar('period', { length: 7 }).notNull(), // e.g. '2026-01'

    // المجاميع (مُحسوبة ومُخزَّنة للأداء)
    totalDebitHalalas: bigint('total_debit_halalas', { mode: 'bigint' })
      .notNull()
      .default(0n),
    totalCreditHalalas: bigint('total_credit_halalas', { mode: 'bigint' })
      .notNull()
      .default(0n),

    // يجب أن يتحقق دائماً: totalDebit === totalCredit
    isBalanced: boolean('is_balanced').notNull().default(false),
    status: journalEntryStatusEnum('status').notNull().default('draft'),

    // هل هذا قيد تلقائي (من المحرك) أم يدوي؟
    isAutoGenerated: boolean('is_auto_generated').notNull().default(true),

    // المرجع
    bookingId: uuid('booking_id').references(() => bookings.id, {
      onDelete: 'set null',
    }),
    invoiceId: uuid('invoice_id'), // self-reference يُحدد لاحقاً

    // القيد العكسي (في حالة الإلغاء)
    reversedByEntryId: uuid('reversed_by_entry_id'),
    reversalOfEntryId: uuid('reversal_of_entry_id'),

    // metadata
    metadata: jsonb('metadata').$type<{
      revenueModel?: string;
      bookingType?: string;
      isInternational?: boolean;
      hadRoundingCorrection?: boolean;
    }>(),

    postedAt: timestamp('posted_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdBy: uuid('created_by').references(() => users.id, {
      onDelete: 'set null',
    }),
  },
  (t) => [
    index('je_agency_id_idx').on(t.agencyId),
    index('je_booking_id_idx').on(t.bookingId),
    index('je_invoice_id_idx').on(t.invoiceId),
    index('je_period_idx').on(t.agencyId, t.period),
    index('je_entry_date_idx').on(t.agencyId, t.entryDate),
    index('je_status_idx').on(t.agencyId, t.status),
    // يمنع حذف أو تعديل القيود المعتمدة (enforcement في RLS)
    check(
      'je_balance_check',
      sql`status = 'draft' OR (is_balanced = true AND total_debit_halalas = total_credit_halalas)`
    ),
  ]
);

/**
 * سطور القيود — Journal Lines
 * كل قيد له سطران على الأقل (مدين + دائن)
 */
export const journalLines = pgTable(
  'journal_lines',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    journalEntryId: uuid('journal_entry_id')
      .notNull()
      .references(() => journalEntries.id, { onDelete: 'cascade' }),
    agencyId: uuid('agency_id')
      .notNull()
      .references(() => agencies.id, { onDelete: 'restrict' }),

    lineNumber: integer('line_number').notNull(),
    accountCode: varchar('account_code', { length: 20 }).notNull(),
    accountNameAr: varchar('account_name_ar', { length: 200 }).notNull(),
    accountNameEn: varchar('account_name_en', { length: 200 }).notNull(),

    // إما debit أو credit — ليس الاثنان
    debitHalalas: bigint('debit_halalas', { mode: 'bigint' })
      .notNull()
      .default(0n),
    creditHalalas: bigint('credit_halalas', { mode: 'bigint' })
      .notNull()
      .default(0n),

    description: text('description'),
    costCenter: varchar('cost_center', { length: 50 }),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    index('jl_journal_entry_id_idx').on(t.journalEntryId),
    index('jl_agency_account_idx').on(t.agencyId, t.accountCode),
    // إما debit أو credit ≥ 0، وليس الاثنان معاً > 0
    check(
      'jl_debit_or_credit_check',
      sql`(debit_halalas = 0 AND credit_halalas > 0) OR (credit_halalas = 0 AND debit_halalas > 0)`
    ),
  ]
);

// ─── الفواتير ─────────────────────────────────────────────────────────────────

/**
 * الفواتير الضريبية — Invoices
 * APPEND-ONLY بعد الإصدار: لا تُحذف، الإلغاء بإنشاء إشعار دائن
 */
export const invoices = pgTable(
  'invoices',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    agencyId: uuid('agency_id')
      .notNull()
      .references(() => agencies.id, { onDelete: 'restrict' }),

    type: invoiceTypeEnum('type').notNull().default('tax_invoice'),
    status: invoiceStatusEnum('status').notNull().default('draft'),

    // رقم الفاتورة (تسلسلي، مطلب ZATCA)
    invoiceNumber: varchar('invoice_number', { length: 30 }).notNull(),
    // UUID فريد لـ ZATCA
    zatcaUuid: uuid('zatca_uuid').notNull().defaultRandom(),

    // الحجز المرتبط
    bookingId: uuid('booking_id').references(() => bookings.id, {
      onDelete: 'restrict',
    }),

    // الفاتورة الأصلية (للإشعارات الدائنة/المدينة)
    originalInvoiceId: uuid('original_invoice_id'),

    // القيد المحاسبي المرتبط
    journalEntryId: uuid('journal_entry_id').references(
      () => journalEntries.id,
      { onDelete: 'set null' }
    ),

    // بيانات البائع (مُنسوخة عند الإصدار — لا تتغير)
    sellerNameAr: varchar('seller_name_ar', { length: 200 }).notNull(),
    sellerNameEn: varchar('seller_name_en', { length: 200 }),
    sellerVatNumber: varchar('seller_vat_number', { length: 15 }).notNull(),
    sellerCrNumber: varchar('seller_cr_number', { length: 20 }),
    sellerAddress: jsonb('seller_address'),

    // بيانات المشتري
    buyerId: uuid('buyer_id').references(() => customers.id, {
      onDelete: 'set null',
    }),
    buyerName: varchar('buyer_name', { length: 200 }).notNull(),
    buyerVatNumber: varchar('buyer_vat_number', { length: 15 }),
    buyerPhone: varchar('buyer_phone', { length: 20 }),

    // المبالغ (بالهللات)
    subtotalExclVatHalalas: bigint('subtotal_excl_vat_halalas', {
      mode: 'bigint',
    })
      .notNull()
      .default(0n),
    totalVatHalalas: bigint('total_vat_halalas', { mode: 'bigint' })
      .notNull()
      .default(0n),
    grandTotalHalalas: bigint('grand_total_halalas', { mode: 'bigint' })
      .notNull()
      .default(0n),
    currency: varchar('currency', { length: 3 }).notNull().default('SAR'),

    // حالة الدفع
    paymentStatus: paymentStatusEnum('payment_status')
      .notNull()
      .default('unpaid'),
    amountPaidHalalas: bigint('amount_paid_halalas', { mode: 'bigint' })
      .notNull()
      .default(0n),
    amountDueHalalas: bigint('amount_due_halalas', { mode: 'bigint' })
      .notNull()
      .default(0n),

    // ZATCA
    zatcaInvoiceTypeCode: zatcaInvoiceTypeCodeEnum('zatca_invoice_type_code')
      .notNull()
      .default('388'),
    zatcaTransactionType: zatcaTransactionTypeEnum('zatca_transaction_type')
      .notNull()
      .default('B2C'),
    zatcaSubmissionStatus: zatcaSubmissionStatusEnum(
      'zatca_submission_status'
    )
      .notNull()
      .default('not_submitted'),
    zatcaXmlHash: text('zatca_xml_hash'), // SHA-256 of signed XML
    zatcaQrCodeData: text('zatca_qr_code_data'), // Base64 TLV QR
    zatcaSignedXmlUrl: text('zatca_signed_xml_url'), // URL in object storage
    zatcaSubmittedAt: timestamp('zatca_submitted_at', { withTimezone: true }),
    zatcaClearanceId: varchar('zatca_clearance_id', { length: 100 }),

    // تواريخ
    issueDate: date('issue_date').notNull(),
    duDate: date('due_date'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdBy: uuid('created_by').references(() => users.id, {
      onDelete: 'set null',
    }),
  },
  (t) => [
    unique('invoices_agency_number_unique').on(t.agencyId, t.invoiceNumber),
    unique('invoices_zatca_uuid_unique').on(t.zatcaUuid),
    index('invoices_agency_id_idx').on(t.agencyId),
    index('invoices_booking_id_idx').on(t.bookingId),
    index('invoices_status_idx').on(t.agencyId, t.status),
    index('invoices_zatca_status_idx').on(t.agencyId, t.zatcaSubmissionStatus),
    index('invoices_issue_date_idx').on(t.agencyId, t.issueDate),
    index('invoices_payment_status_idx').on(t.agencyId, t.paymentStatus),
  ]
);

/**
 * بنود الفاتورة — Invoice Lines
 * كل فاتورة تحتوي على بند واحد على الأقل
 */
export const invoiceLines = pgTable(
  'invoice_lines',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    invoiceId: uuid('invoice_id')
      .notNull()
      .references(() => invoices.id, { onDelete: 'cascade' }),
    agencyId: uuid('agency_id')
      .notNull()
      .references(() => agencies.id, { onDelete: 'restrict' }),

    lineId: varchar('line_id', { length: 10 }).notNull(), // '1', '2', etc.
    name: varchar('name', { length: 300 }).notNull(),
    quantity: integer('quantity').notNull().default(1),
    unitCode: varchar('unit_code', { length: 10 }).notNull().default('PCE'),

    unitPriceExclVatHalalas: bigint('unit_price_excl_vat_halalas', {
      mode: 'bigint',
    })
      .notNull()
      .default(0n),
    totalPriceExclVatHalalas: bigint('total_price_excl_vat_halalas', {
      mode: 'bigint',
    })
      .notNull()
      .default(0n),

    vatCategory: vatCategoryEnum('vat_category').notNull().default('S'),
    vatRateBps: integer('vat_rate_bps').notNull().default(1500), // 1500 = 15%
    vatAmountHalalas: bigint('vat_amount_halalas', { mode: 'bigint' })
      .notNull()
      .default(0n),

    // كود الإعفاء (إن وُجد)
    exemptionReason: varchar('exemption_reason', { length: 50 }),

    // الخصم
    discountAmountHalalas: bigint('discount_amount_halalas', {
      mode: 'bigint',
    })
      .notNull()
      .default(0n),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index('il_invoice_id_idx').on(t.invoiceId)]
);

// ─── عداد الفواتير ────────────────────────────────────────────────────────────

/**
 * عداد أرقام الفواتير — Invoice Counters
 * يحل محل subcollection في Firestore
 * نستخدم PostgreSQL sequence + advisory lock بدلاً من transaction conflict
 */
export const invoiceCounters = pgTable(
  'invoice_counters',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    agencyId: uuid('agency_id')
      .notNull()
      .references(() => agencies.id, { onDelete: 'cascade' }),

    invoiceType: invoiceTypeEnum('invoice_type').notNull(),
    year: integer('year').notNull(),

    // الرقم الحالي — يُحدَّث بـ UPDATE ... RETURNING داخل transaction
    currentSequence: integer('current_sequence').notNull().default(0),

    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    unique('ic_agency_type_year_unique').on(t.agencyId, t.invoiceType, t.year),
    index('ic_agency_id_idx').on(t.agencyId),
  ]
);
